/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { handleAiEmail } from '../fn/ai-controller/handle-ai-email';
import { HandleAiEmail$Params } from '../fn/ai-controller/handle-ai-email';

@Injectable({ providedIn: 'root' })
export class AiControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `handleAiEmail()` */
  static readonly HandleAiEmailPath = '/ai/email';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `handleAiEmail()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  handleAiEmail$Response(params: HandleAiEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
    return handleAiEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `handleAiEmail$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  handleAiEmail(params: HandleAiEmail$Params, context?: HttpContext): Observable<{
[key: string]: string;
}> {
    return this.handleAiEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: string;
}>): {
[key: string]: string;
} => r.body)
    );
  }

}
