/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllLogs } from '../fn/message-log-controller/get-all-logs';
import { GetAllLogs$Params } from '../fn/message-log-controller/get-all-logs';
import { MessageLog } from '../models/message-log';

@Injectable({ providedIn: 'root' })
export class MessageLogControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllLogs()` */
  static readonly GetAllLogsPath = '/admin/logs';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllLogs()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllLogs$Response(params?: GetAllLogs$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MessageLog>>> {
    return getAllLogs(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllLogs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllLogs(params?: GetAllLogs$Params, context?: HttpContext): Observable<Array<MessageLog>> {
    return this.getAllLogs$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MessageLog>>): Array<MessageLog> => r.body)
    );
  }

}
