/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { scheduleMessage } from '../fn/whats-app-controller/schedule-message';
import { ScheduleMessage$Params } from '../fn/whats-app-controller/schedule-message';

@Injectable({ providedIn: 'root' })
export class WhatsAppControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `scheduleMessage()` */
  static readonly ScheduleMessagePath = '/whatsapp/schedule';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `scheduleMessage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  scheduleMessage$Response(params: ScheduleMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return scheduleMessage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `scheduleMessage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  scheduleMessage(params: ScheduleMessage$Params, context?: HttpContext): Observable<string> {
    return this.scheduleMessage$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
