/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MsgResponseDto } from '../../models/msg-response-dto';
import { UpdatedMsgDto } from '../../models/updated-msg-dto';

export interface UpdateMsg$Params {
  id: number;
      body: UpdatedMsgDto
}

export function updateMsg(http: HttpClient, rootUrl: string, params: UpdateMsg$Params, context?: HttpContext): Observable<StrictHttpResponse<MsgResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateMsg.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MsgResponseDto>;
    })
  );
}

updateMsg.PATH = '/timeCapsuleMessage/updateMsg/{id}';
