/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { EmailResponse } from './models/email-response';
export type { GrantedAuthority } from './models/granted-authority';
export type { MessageLog } from './models/message-log';
export type { MsgRequestDto } from './models/msg-request-dto';
export type { MsgResponseDto } from './models/msg-response-dto';
export type { RegisterRequest } from './models/register-request';
export type { UpdatedMsgDto } from './models/updated-msg-dto';
export type { User } from './models/user';
export type { UserDto } from './models/user-dto';
export type { WhatsAppRequestDto } from './models/whats-app-request-dto';
