/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageLog } from '../../models/message-log';

export interface GetAllLogs$Params {
}

export function getAllLogs(http: HttpClient, rootUrl: string, params?: GetAllLogs$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MessageLog>>> {
  const rb = new RequestBuilder(rootUrl, getAllLogs.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MessageLog>>;
    })
  );
}

getAllLogs.PATH = '/admin/logs';
