/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmailResponse {
  jobGroup?: string;
  jobId?: string;
  message?: string;
  success?: boolean;
}
