/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageLog {
  errorMessage?: string;
  id?: number;
  messageId?: number;
  status?: 'PENDING' | 'SENT' | 'FAILED';
  timestamp?: string;
}
