/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MsgResponseDto {
  attachmentPath?: string;
  content?: string;
  createdAt?: string;
  id?: number;
  recipientEmail?: string;
  scheduledDate?: string;
  status?: 'PENDING' | 'SENT' | 'FAILED';
  subject?: string;
  updatedAt?: string;
}
