/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MsgRequestDto {
  content?: string;
  recipientEmail: string;
  scheduledDate: string;
  subject?: string;
}
