/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {
  email: string;
  password: string;
  role?: 'ADMIN' | 'USER';
  username: string;
}
