/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  email?: string;
  id?: number;
  role?: 'ADMIN' | 'USER';
  username?: string;
}
